### PR TITLE
$position missing from template

### PR DESCRIPTION
**Pull request by ahosker**
Had a few issues with this, comparing it to other packages. I could see $position was missing from the file.

### CODE REVIEW

**Comment by freekmurze** [comment]
I'm thinking this isn't needed anymore in Livewire 2 as it will automatically put all html attributes as public properties on the component.

**Comment by ahosker** [comment]
If that is the case, it's working for me. Without this in place I receive:
`ErrorException: Undefined variable: position`
With it, the tile works.

**Comment by freekmurze** [comment]
Do you have Livewire 2 installed?

**Comment by ahosker** [comment]
Yes, a brand new Laravel Jetstream, Livewire Stack includes V2.

**Comment by freekmurze** [comment]
I'll re-add it for now, and will investigate myself later.

**Pull request merged**
